source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BFTaskCenter_Example', :exclusive => true do
  pod 'BFTaskCenter', :path => '../'
end

target 'BFTaskCenter_Tests', :exclusive => true do
  pod 'BFTaskCenter', :path => '../'

  
end
