language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: Example/Podfile
before_install:
  - rvm install 2.2.2
  - rvm use 2.2.2
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  # - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/BFTaskCenter.xcworkspace -scheme BFTaskCenter-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
